apiVersion: v1
kind: Pod
metadata:
  name: hostpath-demo
spec:
  containers:
    - name: app
      image: nginx:1.27
      volumeMounts:
        - name: host-storage
          mountPath: /shubham-data
  volumes:
    - name: host-storage
      hostPath:
        path: /tmp/shubham-hostpath-data
        type: DirectoryOrCreate
